const Map<String, Map<String, String>> notificationStrings = {
  'sv': {
    'body_now': 'Nu är det dags att {action}',
    'body_pre': 'Om en vecka är det dags att {action}',
    'action_forsa': 'förså inomhus',
    'action_direkt': 'direktså',
    'action_utplant': 'plantera ut',
    'action_skord': 'skörda',
    'label_forsa': 'Förså inomhus',
    'label_direkt': 'Direktså',
    'label_utplant': 'Plantera ut',
    'label_skord': 'Skörda',
    'label_harden': 'Härda av',
    'wishlist_body': 'Nu öppnar säsongen för att {action} – tryck för att lägga till i trädgården.',
    'wishlist_pre': 'Om en vecka är det dags att {action} – köp frön i tid.',
    'harden_body': 'Dags att börja härda av — ställ ut plantorna ett par timmar dagligen i en vecka.',
    'care_body': '{title} – {description}',
    'care_pre': 'Om en vecka: {title}',
    'digest_title': '🌱 Trädgårdsmorgon',
    'digest_body_one': 'I {month}: {line}.',
    'digest_body_many': 'I {month}: {lines}{more}',
    'digest_more': ' m.fl.',
    'digest_end_dot': '.',
    'month_1': 'januari',
    'month_2': 'februari',
    'month_3': 'mars',
    'month_4': 'april',
    'month_5': 'maj',
    'month_6': 'juni',
    'month_7': 'juli',
    'month_8': 'augusti',
    'month_9': 'september',
    'month_10': 'oktober',
    'month_11': 'november',
    'month_12': 'december',
    'frost_title': '❄️ Frostvarning i natt',
    'frost_body_one': 'I natt väntas {temp}°C – täck dina {name}.',
    'frost_body_many': 'I natt väntas {temp}°C – täck {names}{more}.',
    'heatwave_title': '🔥 Värmebölja på väg',
    'heatwave_body': 'Flera varma dagar väntas – vattna noga, skugga känsliga växter och kontrollera krukor dagligen.',
    'dry_title': '☀️ Torrperiod pågår',
    'dry_body_historical': 'Endast {mm} mm regn senaste 14 dagar och lite på väg – vattna noga, särskilt nyplanterade och i krukor.',
    'dry_body_forecast': 'Mycket lite nederbörd väntas kommande vecka – håll koll på vattningen, särskilt nyplanterade och i krukor.',
    'campaign_feb_title': '🍅 Dags att förodla tomater',
    'campaign_feb_body': 'Februari–mars är peak-tid för att starta tomater och chili inomhus.',
    'campaign_mar_title': '🌱 Direktså snart',
    'campaign_mar_body': 'Morötter, ärtor och spenat kan direktsås så snart jorden tinat.',
    'campaign_apr_title': '🪴 Plantera ut fönstret öppnas',
    'campaign_apr_body': 'Härda av plantorna och förbered jorden — utplantering börjar nu.',
    'campaign_jul_title': '🥕 Skördetid!',
    'campaign_jul_body': 'Logga din första skörd och se hur mycket din trädgård är värd.',
    'campaign_sep_title': '🌷 Sätt vårblommande lökar',
    'campaign_sep_body': 'Tulpan, narciss och krokus sätts nu för en blomstrande vår.',
    'campaign_nov_title': '📓 Reflektera över årets odling',
    'campaign_nov_body': 'Vad gick bra? Skriv ner — minnet sviker till våren.',
  },
  'en': {
    'body_now': 'It\'s time to {action}',
    'body_pre': 'In one week it\'s time to {action}',
    'action_forsa': 'start indoors',
    'action_direkt': 'direct sow',
    'action_utplant': 'plant out',
    'action_skord': 'harvest',
    'label_forsa': 'Start indoors',
    'label_direkt': 'Direct sow',
    'label_utplant': 'Plant out',
    'label_skord': 'Harvest',
    'label_harden': 'Harden off',
    'wishlist_body': 'The season is now open to {action} – tap to add to your garden.',
    'wishlist_pre': 'In one week it\'s time to {action} – buy seeds in good time.',
    'harden_body': 'Time to start hardening off — set the seedlings outside for a couple of hours daily for a week.',
    'care_body': '{title} – {description}',
    'care_pre': 'In one week: {title}',
    'digest_title': '🌱 Garden morning',
    'digest_body_one': 'In {month}: {line}.',
    'digest_body_many': 'In {month}: {lines}{more}',
    'digest_more': ' and more',
    'digest_end_dot': '.',
    'month_1': 'january',
    'month_2': 'february',
    'month_3': 'march',
    'month_4': 'april',
    'month_5': 'may',
    'month_6': 'june',
    'month_7': 'july',
    'month_8': 'august',
    'month_9': 'september',
    'month_10': 'october',
    'month_11': 'november',
    'month_12': 'december',
    'frost_title': '❄️ Frost warning tonight',
    'frost_body_one': 'Tonight {temp}°C is expected – cover your {name}.',
    'frost_body_many': 'Tonight {temp}°C is expected – cover {names}{more}.',
    'heatwave_title': '🔥 Heatwave on the way',
    'heatwave_body': 'Several hot days are expected – water carefully, shade sensitive plants and check pots daily.',
    'dry_title': '☀️ Dry spell ongoing',
    'dry_body_historical': 'Only {mm} mm of rain in the last 14 days and little on the way – water carefully, especially newly planted and in pots.',
    'dry_body_forecast': 'Very little precipitation expected next week – keep an eye on watering, especially newly planted and in pots.',
    'campaign_feb_title': '🍅 Time to pre-sow tomatoes',
    'campaign_feb_body': 'February–March is peak time to start tomatoes and chilli indoors.',
    'campaign_mar_title': '🌱 Direct sow soon',
    'campaign_mar_body': 'Carrots, peas and spinach can be direct sown as soon as the soil has thawed.',
    'campaign_apr_title': '🪴 The plant-out window opens',
    'campaign_apr_body': 'Harden off the seedlings and prepare the soil — transplanting starts now.',
    'campaign_jul_title': '🥕 Harvest time!',
    'campaign_jul_body': 'Log your first harvest and see how much your garden is worth.',
    'campaign_sep_title': '🌷 Plant spring-flowering bulbs',
    'campaign_sep_body': 'Tulips, daffodils and crocuses are planted now for a blooming spring.',
    'campaign_nov_title': '📓 Reflect on this year\'s growing',
    'campaign_nov_body': 'What went well? Write it down — memory fails by spring.',
  },
  'nb': {
    'body_now': 'Nå er det på tide å {action}',
    'body_pre': 'Om en uke er det på tide å {action}',
    'action_forsa': 'forså inne',
    'action_direkt': 'direktså',
    'action_utplant': 'plante ut',
    'action_skord': 'høste',
    'label_forsa': 'Forså inne',
    'label_direkt': 'Direktså',
    'label_utplant': 'Plante ut',
    'label_skord': 'Høste',
    'label_harden': 'Herde av',
    'wishlist_body': 'Sesongen åpner nå for å {action} – trykk for å legge til i hagen.',
    'wishlist_pre': 'Om en uke er det på tide å {action} – kjøp frø i tide.',
    'harden_body': 'På tide å begynne å herde av — sett plantene ut et par timer daglig i en uke.',
    'care_body': '{title} – {description}',
    'care_pre': 'Om en uke: {title}',
    'digest_title': '🌱 Hagemorgen',
    'digest_body_one': 'I {month}: {line}.',
    'digest_body_many': 'I {month}: {lines}{more}',
    'digest_more': ' m.fl.',
    'digest_end_dot': '.',
    'month_1': 'januar',
    'month_2': 'februar',
    'month_3': 'mars',
    'month_4': 'april',
    'month_5': 'mai',
    'month_6': 'juni',
    'month_7': 'juli',
    'month_8': 'august',
    'month_9': 'september',
    'month_10': 'oktober',
    'month_11': 'november',
    'month_12': 'desember',
    'frost_title': '❄️ Frostvarsel i natt',
    'frost_body_one': 'I natt ventes {temp}°C – dekk til {name}.',
    'frost_body_many': 'I natt ventes {temp}°C – dekk til {names}{more}.',
    'heatwave_title': '🔥 Hetebølge på vei',
    'heatwave_body': 'Flere varme dager ventes – vann grundig, gi skygge til sårbare planter og sjekk potter daglig.',
    'dry_title': '☀️ Tørkeperiode pågår',
    'dry_body_historical': 'Bare {mm} mm regn de siste 14 dagene og lite på vei – vann grundig, særlig nyplantede og i potter.',
    'dry_body_forecast': 'Svært lite nedbør ventes den kommende uken – hold øye med vanningen, særlig nyplantede og i potter.',
    'campaign_feb_title': '🍅 På tide å forså tomater',
    'campaign_feb_body': 'Februar–mars er beste tid for å starte tomater og chili inne.',
    'campaign_mar_title': '🌱 Direktså snart',
    'campaign_mar_body': 'Gulrøtter, erter og spinat kan direktsås så snart jorden har tint.',
    'campaign_apr_title': '🪴 Utplantingsvinduet åpner seg',
    'campaign_apr_body': 'Herd av plantene og klargjør jorden — utplanting starter nå.',
    'campaign_jul_title': '🥕 Innhøstingstid!',
    'campaign_jul_body': 'Logg din første høst og se hvor mye hagen din er verdt.',
    'campaign_sep_title': '🌷 Sett vårblomstrende løker',
    'campaign_sep_body': 'Tulipan, påskelilje og krokus settes nå for en blomstrende vår.',
    'campaign_nov_title': '📓 Reflekter over årets dyrking',
    'campaign_nov_body': 'Hva gikk bra? Skriv det ned — minnet svikter til våren.',
  },
  'da': {
    'body_now': 'Nu er det tid til at {action}',
    'body_pre': 'Om en uge er det tid til at {action}',
    'action_forsa': 'forså indendørs',
    'action_direkt': 'direkte så',
    'action_utplant': 'plante ud',
    'action_skord': 'høste',
    'label_forsa': 'Forså indendørs',
    'label_direkt': 'Direkte så',
    'label_utplant': 'Plante ud',
    'label_skord': 'Høste',
    'label_harden': 'Afhærde',
    'wishlist_body': 'Sæsonen åbner nu for at {action} – tryk for at føje til haven.',
    'wishlist_pre': 'Om en uge er det tid til at {action} – køb frø i god tid.',
    'harden_body': 'Tid til at begynde at afhærde — sæt planterne ud et par timer dagligt i en uge.',
    'care_body': '{title} – {description}',
    'care_pre': 'Om en uge: {title}',
    'digest_title': '🌱 Havemorgen',
    'digest_body_one': 'I {month}: {line}.',
    'digest_body_many': 'I {month}: {lines}{more}',
    'digest_more': ' m.fl.',
    'digest_end_dot': '.',
    'month_1': 'januar',
    'month_2': 'februar',
    'month_3': 'marts',
    'month_4': 'april',
    'month_5': 'maj',
    'month_6': 'juni',
    'month_7': 'juli',
    'month_8': 'august',
    'month_9': 'september',
    'month_10': 'oktober',
    'month_11': 'november',
    'month_12': 'december',
    'frost_title': '❄️ Frostvarsel i nat',
    'frost_body_one': 'I nat ventes {temp}°C – dæk dine {name}.',
    'frost_body_many': 'I nat ventes {temp}°C – dæk {names}{more}.',
    'heatwave_title': '🔥 Hedebølge på vej',
    'heatwave_body': 'Flere varme dage ventes – vand grundigt, skyg følsomme planter og tjek krukker dagligt.',
    'dry_title': '☀️ Tørkeperiode i gang',
    'dry_body_historical': 'Kun {mm} mm regn de seneste 14 dage og lidt på vej – vand grundigt, især nyplantede og i krukker.',
    'dry_body_forecast': 'Meget lidt nedbør ventes den kommende uge – hold øje med vandingen, især nyplantede og i krukker.',
    'campaign_feb_title': '🍅 Tid til at forså tomater',
    'campaign_feb_body': 'Februar–marts er bedste tid til at starte tomater og chili indendørs.',
    'campaign_mar_title': '🌱 Direkte så snart',
    'campaign_mar_body': 'Gulerødder, ærter og spinat kan direkte sås, så snart jorden er tøet.',
    'campaign_apr_title': '🪴 Udplantningsvinduet åbner',
    'campaign_apr_body': 'Afhærd planterne og forbered jorden — udplantning starter nu.',
    'campaign_jul_title': '🥕 Høsttid!',
    'campaign_jul_body': 'Log din første høst og se, hvor meget din have er værd.',
    'campaign_sep_title': '🌷 Sæt forårsblomstrende løg',
    'campaign_sep_body': 'Tulipan, påskelilje og krokus sættes nu til et blomstrende forår.',
    'campaign_nov_title': '📓 Reflektér over årets dyrkning',
    'campaign_nov_body': 'Hvad gik godt? Skriv det ned — hukommelsen svigter til foråret.',
  },
  'fi': {
    'body_now': 'Nyt on aika {action}',
    'body_pre': 'Viikon päästä on aika {action}',
    'action_forsa': 'esikylvää sisällä',
    'action_direkt': 'kylvää suoraan',
    'action_utplant': 'istuttaa ulos',
    'action_skord': 'sadonkorjuuseen',
    'label_forsa': 'Esikylvä sisällä',
    'label_direkt': 'Suorakylvö',
    'label_utplant': 'Istuta ulos',
    'label_skord': 'Korjaa sato',
    'label_harden': 'Karaise taimet',
    'wishlist_body': 'Kausi avautuu nyt: {action} – napauta lisätäksesi puutarhaan.',
    'wishlist_pre': 'Viikon päästä on aika {action} – osta siemenet ajoissa.',
    'harden_body': 'Aika alkaa karaista taimia — pidä niitä ulkona pari tuntia päivässä viikon ajan.',
    'care_body': '{title} – {description}',
    'care_pre': 'Viikon päästä: {title}',
    'digest_title': '🌱 Puutarha-aamu',
    'digest_body_one': 'Kuukaudessa {month}: {line}.',
    'digest_body_many': 'Kuukaudessa {month}: {lines}{more}',
    'digest_more': ' ym.',
    'digest_end_dot': '.',
    'month_1': 'tammikuu',
    'month_2': 'helmikuu',
    'month_3': 'maaliskuu',
    'month_4': 'huhtikuu',
    'month_5': 'toukokuu',
    'month_6': 'kesäkuu',
    'month_7': 'heinäkuu',
    'month_8': 'elokuu',
    'month_9': 'syyskuu',
    'month_10': 'lokakuu',
    'month_11': 'marraskuu',
    'month_12': 'joulukuu',
    'frost_title': '❄️ Hallavaroitus yöksi',
    'frost_body_one': 'Yöllä odotetaan {temp}°C – peitä {name}.',
    'frost_body_many': 'Yöllä odotetaan {temp}°C – peitä {names}{more}.',
    'heatwave_title': '🔥 Helleaalto tulossa',
    'heatwave_body': 'Useita kuumia päiviä luvassa – kastele huolella, varjosta arat kasvit ja tarkista ruukut päivittäin.',
    'dry_title': '☀️ Kuiva kausi käynnissä',
    'dry_body_historical': 'Vain {mm} mm sadetta viimeisen 14 päivän aikana ja vähän tulossa – kastele huolella, erityisesti uudet istutukset ja ruukut.',
    'dry_body_forecast': 'Hyvin vähän sadetta odotettavissa ensi viikolla – pidä huolta kastelusta, erityisesti uudet istutukset ja ruukut.',
    'campaign_feb_title': '🍅 Aika esikylvää tomaatit',
    'campaign_feb_body': 'Helmi–maaliskuu on parasta aikaa aloittaa tomaatit ja chilit sisällä.',
    'campaign_mar_title': '🌱 Suorakylvö pian',
    'campaign_mar_body': 'Porkkanat, herneet ja pinaatti voidaan suorakylvää heti kun maa on sulanut.',
    'campaign_apr_title': '🪴 Istutusikkuna avautuu',
    'campaign_apr_body': 'Karaise taimet ja valmistele maa — istutus alkaa nyt.',
    'campaign_jul_title': '🥕 Sadonkorjuun aika!',
    'campaign_jul_body': 'Kirjaa ensimmäinen satosi ja katso, paljonko puutarhasi on arvoltaan.',
    'campaign_sep_title': '🌷 Istuta kevätkukkivat sipulit',
    'campaign_sep_body': 'Tulppaanit, narsissit ja krookukset istutetaan nyt kukoistavaa kevättä varten.',
    'campaign_nov_title': '📓 Pohdi tämän vuoden viljelyä',
    'campaign_nov_body': 'Mikä meni hyvin? Kirjoita ylös — muisti pettää kevääseen mennessä.',
  },
  'de': {
    'body_now': 'Jetzt ist es Zeit, {action}',
    'body_pre': 'In einer Woche ist es Zeit, {action}',
    'action_forsa': 'drinnen vorzuziehen',
    'action_direkt': 'direkt zu säen',
    'action_utplant': 'auszupflanzen',
    'action_skord': 'zu ernten',
    'label_forsa': 'Drinnen vorziehen',
    'label_direkt': 'Direktsaat',
    'label_utplant': 'Auspflanzen',
    'label_skord': 'Ernten',
    'label_harden': 'Abhärten',
    'wishlist_body': 'Die Saison öffnet sich jetzt, um {action} – tippe, um zum Garten hinzuzufügen.',
    'wishlist_pre': 'In einer Woche ist es Zeit, {action} – Samen rechtzeitig kaufen.',
    'harden_body': 'Zeit, mit dem Abhärten zu beginnen — stelle die Pflanzen täglich ein paar Stunden für eine Woche nach draußen.',
    'care_body': '{title} – {description}',
    'care_pre': 'In einer Woche: {title}',
    'digest_title': '🌱 Gartenmorgen',
    'digest_body_one': 'Im {month}: {line}.',
    'digest_body_many': 'Im {month}: {lines}{more}',
    'digest_more': ' u.a.',
    'digest_end_dot': '.',
    'month_1': 'januar',
    'month_2': 'februar',
    'month_3': 'märz',
    'month_4': 'april',
    'month_5': 'mai',
    'month_6': 'juni',
    'month_7': 'juli',
    'month_8': 'august',
    'month_9': 'september',
    'month_10': 'oktober',
    'month_11': 'november',
    'month_12': 'dezember',
    'frost_title': '❄️ Frostwarnung heute Nacht',
    'frost_body_one': 'Heute Nacht werden {temp}°C erwartet – decke deine {name} ab.',
    'frost_body_many': 'Heute Nacht werden {temp}°C erwartet – decke {names}{more} ab.',
    'heatwave_title': '🔥 Hitzewelle im Anmarsch',
    'heatwave_body': 'Mehrere heiße Tage werden erwartet – gründlich gießen, empfindliche Pflanzen beschatten und Töpfe täglich kontrollieren.',
    'dry_title': '☀️ Trockenperiode hält an',
    'dry_body_historical': 'Nur {mm} mm Regen in den letzten 14 Tagen und wenig in Sicht – gründlich gießen, besonders Neupflanzungen und Töpfe.',
    'dry_body_forecast': 'Sehr wenig Niederschlag in der kommenden Woche erwartet – Bewässerung im Auge behalten, besonders Neupflanzungen und Töpfe.',
    'campaign_feb_title': '🍅 Zeit, Tomaten vorzuziehen',
    'campaign_feb_body': 'Februar–März ist die beste Zeit, um Tomaten und Chili drinnen zu starten.',
    'campaign_mar_title': '🌱 Bald direkt säen',
    'campaign_mar_body': 'Karotten, Erbsen und Spinat können direkt gesät werden, sobald der Boden aufgetaut ist.',
    'campaign_apr_title': '🪴 Das Auspflanzfenster öffnet sich',
    'campaign_apr_body': 'Pflanzen abhärten und Boden vorbereiten — das Auspflanzen beginnt jetzt.',
    'campaign_jul_title': '🥕 Erntezeit!',
    'campaign_jul_body': 'Trage deine erste Ernte ein und sieh, wie viel dein Garten wert ist.',
    'campaign_sep_title': '🌷 Frühjahrsblüher-Zwiebeln setzen',
    'campaign_sep_body': 'Tulpen, Narzissen und Krokusse werden jetzt für einen blühenden Frühling gesetzt.',
    'campaign_nov_title': '📓 Reflektiere über das Gartenjahr',
    'campaign_nov_body': 'Was lief gut? Schreib es auf — bis zum Frühling vergisst man es.',
  },
  'fr': {
    'body_now': 'C\'est le moment de {action}',
    'body_pre': 'Dans une semaine, c\'est le moment de {action}',
    'action_forsa': 'semer en intérieur',
    'action_direkt': 'semer en pleine terre',
    'action_utplant': 'repiquer',
    'action_skord': 'récolter',
    'label_forsa': 'Semer en intérieur',
    'label_direkt': 'Semis direct',
    'label_utplant': 'Repiquer',
    'label_skord': 'Récolter',
    'label_harden': 'Acclimater',
    'wishlist_body': 'La saison s\'ouvre pour {action} – appuie pour ajouter au jardin.',
    'wishlist_pre': 'Dans une semaine, il sera temps de {action} – achète les graines à temps.',
    'harden_body': 'Il est temps de commencer à acclimater — sors les plants quelques heures par jour pendant une semaine.',
    'care_body': '{title} – {description}',
    'care_pre': 'Dans une semaine : {title}',
    'digest_title': '🌱 Matin au jardin',
    'digest_body_one': 'En {month} : {line}.',
    'digest_body_many': 'En {month} : {lines}{more}',
    'digest_more': ' etc.',
    'digest_end_dot': '.',
    'month_1': 'janvier',
    'month_2': 'février',
    'month_3': 'mars',
    'month_4': 'avril',
    'month_5': 'mai',
    'month_6': 'juin',
    'month_7': 'juillet',
    'month_8': 'août',
    'month_9': 'septembre',
    'month_10': 'octobre',
    'month_11': 'novembre',
    'month_12': 'décembre',
    'frost_title': '❄️ Alerte gel cette nuit',
    'frost_body_one': 'Cette nuit, {temp}°C sont prévus – protège tes {name}.',
    'frost_body_many': 'Cette nuit, {temp}°C sont prévus – protège {names}{more}.',
    'heatwave_title': '🔥 Canicule en approche',
    'heatwave_body': 'Plusieurs journées chaudes sont prévues – arrose bien, ombre les plantes sensibles et vérifie les pots chaque jour.',
    'dry_title': '☀️ Période de sécheresse en cours',
    'dry_body_historical': 'Seulement {mm} mm de pluie ces 14 derniers jours et peu à venir – arrose bien, surtout les nouvelles plantations et les pots.',
    'dry_body_forecast': 'Très peu de précipitations prévues la semaine prochaine – surveille l\'arrosage, surtout les nouvelles plantations et les pots.',
    'campaign_feb_title': '🍅 Il est temps de semer les tomates',
    'campaign_feb_body': 'Février–mars est la période idéale pour démarrer tomates et piments en intérieur.',
    'campaign_mar_title': '🌱 Semis direct bientôt',
    'campaign_mar_body': 'Carottes, pois et épinards peuvent être semés en pleine terre dès que le sol est dégelé.',
    'campaign_apr_title': '🪴 La fenêtre de repiquage s\'ouvre',
    'campaign_apr_body': 'Acclimate les plants et prépare le sol — le repiquage commence maintenant.',
    'campaign_jul_title': '🥕 Heure de la récolte !',
    'campaign_jul_body': 'Enregistre ta première récolte et vois la valeur de ton jardin.',
    'campaign_sep_title': '🌷 Plante les bulbes de printemps',
    'campaign_sep_body': 'Tulipes, narcisses et crocus se plantent maintenant pour un printemps fleuri.',
    'campaign_nov_title': '📓 Réfléchis à l\'année de culture',
    'campaign_nov_body': 'Qu\'est-ce qui a bien marché ? Note-le — la mémoire fait défaut au printemps.',
  },
  'es': {
    'body_now': 'Es hora de {action}',
    'body_pre': 'En una semana es hora de {action}',
    'action_forsa': 'sembrar en interior',
    'action_direkt': 'sembrar directamente',
    'action_utplant': 'trasplantar al exterior',
    'action_skord': 'cosechar',
    'label_forsa': 'Sembrar en interior',
    'label_direkt': 'Siembra directa',
    'label_utplant': 'Trasplantar',
    'label_skord': 'Cosechar',
    'label_harden': 'Endurecer',
    'wishlist_body': 'Se abre la temporada para {action} – toca para añadir al jardín.',
    'wishlist_pre': 'En una semana es hora de {action} – compra las semillas con tiempo.',
    'harden_body': 'Hora de empezar a endurecer las plantas — sácalas un par de horas al día durante una semana.',
    'care_body': '{title} – {description}',
    'care_pre': 'En una semana: {title}',
    'digest_title': '🌱 Mañana en el jardín',
    'digest_body_one': 'En {month}: {line}.',
    'digest_body_many': 'En {month}: {lines}{more}',
    'digest_more': ' etc.',
    'digest_end_dot': '.',
    'month_1': 'enero',
    'month_2': 'febrero',
    'month_3': 'marzo',
    'month_4': 'abril',
    'month_5': 'mayo',
    'month_6': 'junio',
    'month_7': 'julio',
    'month_8': 'agosto',
    'month_9': 'septiembre',
    'month_10': 'octubre',
    'month_11': 'noviembre',
    'month_12': 'diciembre',
    'frost_title': '❄️ Aviso de heladas esta noche',
    'frost_body_one': 'Esta noche se esperan {temp}°C – cubre tus {name}.',
    'frost_body_many': 'Esta noche se esperan {temp}°C – cubre {names}{more}.',
    'heatwave_title': '🔥 Ola de calor en camino',
    'heatwave_body': 'Se esperan varios días calurosos – riega a fondo, da sombra a las plantas sensibles y revisa las macetas a diario.',
    'dry_title': '☀️ Periodo de sequía en curso',
    'dry_body_historical': 'Solo {mm} mm de lluvia en los últimos 14 días y poca prevista – riega a fondo, sobre todo las recién plantadas y las macetas.',
    'dry_body_forecast': 'Se espera muy poca precipitación la próxima semana – vigila el riego, sobre todo las recién plantadas y las macetas.',
    'campaign_feb_title': '🍅 Hora de sembrar tomates',
    'campaign_feb_body': 'Febrero–marzo es el mejor momento para empezar tomates y chiles en interior.',
    'campaign_mar_title': '🌱 Siembra directa pronto',
    'campaign_mar_body': 'Zanahorias, guisantes y espinacas se pueden sembrar directamente en cuanto el suelo se descongele.',
    'campaign_apr_title': '🪴 Se abre la ventana de trasplante',
    'campaign_apr_body': 'Endurece las plantas y prepara la tierra — el trasplante empieza ahora.',
    'campaign_jul_title': '🥕 ¡Tiempo de cosecha!',
    'campaign_jul_body': 'Registra tu primera cosecha y mira cuánto vale tu jardín.',
    'campaign_sep_title': '🌷 Planta bulbos de primavera',
    'campaign_sep_body': 'Tulipanes, narcisos y crocos se plantan ahora para una primavera florecida.',
    'campaign_nov_title': '📓 Reflexiona sobre el cultivo del año',
    'campaign_nov_body': '¿Qué salió bien? Apúntalo — la memoria falla para la primavera.',
  },
  'it': {
    'body_now': 'È ora di {action}',
    'body_pre': 'Tra una settimana è ora di {action}',
    'action_forsa': 'seminare in casa',
    'action_direkt': 'seminare in piena terra',
    'action_utplant': 'trapiantare all\'aperto',
    'action_skord': 'raccogliere',
    'label_forsa': 'Semina in casa',
    'label_direkt': 'Semina diretta',
    'label_utplant': 'Trapianta',
    'label_skord': 'Raccogli',
    'label_harden': 'Indurire le piante',
    'wishlist_body': 'Si apre la stagione per {action} – tocca per aggiungere al giardino.',
    'wishlist_pre': 'Tra una settimana è ora di {action} – compra i semi in tempo.',
    'harden_body': 'È ora di iniziare l\'indurimento — porta le piantine all\'aperto un paio d\'ore al giorno per una settimana.',
    'care_body': '{title} – {description}',
    'care_pre': 'Tra una settimana: {title}',
    'digest_title': '🌱 Mattino in giardino',
    'digest_body_one': 'A {month}: {line}.',
    'digest_body_many': 'A {month}: {lines}{more}',
    'digest_more': ' ecc.',
    'digest_end_dot': '.',
    'month_1': 'gennaio',
    'month_2': 'febbraio',
    'month_3': 'marzo',
    'month_4': 'aprile',
    'month_5': 'maggio',
    'month_6': 'giugno',
    'month_7': 'luglio',
    'month_8': 'agosto',
    'month_9': 'settembre',
    'month_10': 'ottobre',
    'month_11': 'novembre',
    'month_12': 'dicembre',
    'frost_title': '❄️ Allerta gelo stanotte',
    'frost_body_one': 'Stanotte sono attesi {temp}°C – copri le tue {name}.',
    'frost_body_many': 'Stanotte sono attesi {temp}°C – copri {names}{more}.',
    'heatwave_title': '🔥 Ondata di calore in arrivo',
    'heatwave_body': 'Sono previsti diversi giorni caldi – innaffia bene, ombreggia le piante sensibili e controlla i vasi ogni giorno.',
    'dry_title': '☀️ Periodo di siccità in corso',
    'dry_body_historical': 'Solo {mm} mm di pioggia negli ultimi 14 giorni e poca in arrivo – innaffia bene, soprattutto le nuove piantagioni e i vasi.',
    'dry_body_forecast': 'Pochissime precipitazioni previste la prossima settimana – attenzione all\'irrigazione, soprattutto per le nuove piantagioni e i vasi.',
    'campaign_feb_title': '🍅 È ora di seminare i pomodori',
    'campaign_feb_body': 'Febbraio–marzo è il momento migliore per avviare pomodori e peperoncini in casa.',
    'campaign_mar_title': '🌱 Semina diretta presto',
    'campaign_mar_body': 'Carote, piselli e spinaci si possono seminare direttamente appena il terreno è sgelato.',
    'campaign_apr_title': '🪴 Si apre la finestra del trapianto',
    'campaign_apr_body': 'Indurisci le piantine e prepara il terreno — il trapianto inizia adesso.',
    'campaign_jul_title': '🥕 Tempo di raccolta!',
    'campaign_jul_body': 'Registra il tuo primo raccolto e vedi quanto vale il tuo giardino.',
    'campaign_sep_title': '🌷 Pianta i bulbi a fioritura primaverile',
    'campaign_sep_body': 'Tulipani, narcisi e crochi si piantano adesso per una primavera fiorita.',
    'campaign_nov_title': '📓 Rifletti sulla coltivazione dell\'anno',
    'campaign_nov_body': 'Cosa è andato bene? Scrivilo — la memoria viene meno entro primavera.',
  },
  'el': {
    'body_now': 'Τώρα είναι ώρα να {action}',
    'body_pre': 'Σε μία εβδομάδα είναι ώρα να {action}',
    'action_forsa': 'σπείρετε σε εσωτερικό χώρο',
    'action_direkt': 'σπείρετε απευθείας',
    'action_utplant': 'μεταφυτέψετε έξω',
    'action_skord': 'συγκομίσετε',
    'label_forsa': 'Σπορά σε εσωτερικό χώρο',
    'label_direkt': 'Απευθείας σπορά',
    'label_utplant': 'Μεταφύτευση',
    'label_skord': 'Συγκομιδή',
    'label_harden': 'Σκληραγώγηση',
    'wishlist_body': 'Η εποχή ανοίγει τώρα για να {action} – πατήστε για προσθήκη στον κήπο.',
    'wishlist_pre': 'Σε μία εβδομάδα είναι ώρα να {action} – αγοράστε σπόρους εγκαίρως.',
    'harden_body': 'Ώρα να ξεκινήσει η σκληραγώγηση — βγάλτε τα φυτά έξω για μερικές ώρες την ημέρα για μία εβδομάδα.',
    'care_body': '{title} – {description}',
    'care_pre': 'Σε μία εβδομάδα: {title}',
    'digest_title': '🌱 Πρωινό στον κήπο',
    'digest_body_one': 'Τον {month}: {line}.',
    'digest_body_many': 'Τον {month}: {lines}{more}',
    'digest_more': ' κ.ά.',
    'digest_end_dot': '.',
    'month_1': 'ιανουάριος',
    'month_2': 'φεβρουάριος',
    'month_3': 'μάρτιος',
    'month_4': 'απρίλιος',
    'month_5': 'μάιος',
    'month_6': 'ιούνιος',
    'month_7': 'ιούλιος',
    'month_8': 'αύγουστος',
    'month_9': 'σεπτέμβριος',
    'month_10': 'οκτώβριος',
    'month_11': 'νοέμβριος',
    'month_12': 'δεκέμβριος',
    'frost_title': '❄️ Προειδοποίηση παγετού απόψε',
    'frost_body_one': 'Απόψε αναμένονται {temp}°C – καλύψτε τα {name} σας.',
    'frost_body_many': 'Απόψε αναμένονται {temp}°C – καλύψτε {names}{more}.',
    'heatwave_title': '🔥 Καύσωνας στον δρόμο',
    'heatwave_body': 'Αναμένονται αρκετές ζεστές ημέρες – ποτίστε καλά, σκιάστε τα ευαίσθητα φυτά και ελέγχετε τις γλάστρες καθημερινά.',
    'dry_title': '☀️ Περίοδος ξηρασίας σε εξέλιξη',
    'dry_body_historical': 'Μόνο {mm} mm βροχής τις τελευταίες 14 ημέρες και λίγη στον δρόμο – ποτίστε καλά, ιδιαίτερα τα νεοφυτεμένα και τις γλάστρες.',
    'dry_body_forecast': 'Πολύ λίγες βροχοπτώσεις αναμένονται την επόμενη εβδομάδα – προσέξτε το πότισμα, ιδιαίτερα τα νεοφυτεμένα και τις γλάστρες.',
    'campaign_feb_title': '🍅 Ώρα για προσπορά ντομάτας',
    'campaign_feb_body': 'Φεβρουάριος–Μάρτιος είναι η κορυφαία περίοδος για να ξεκινήσετε ντομάτες και τσίλι σε εσωτερικό χώρο.',
    'campaign_mar_title': '🌱 Σύντομα απευθείας σπορά',
    'campaign_mar_body': 'Καρότα, μπιζέλια και σπανάκι μπορούν να σπαρθούν απευθείας μόλις λιώσει το χώμα.',
    'campaign_apr_title': '🪴 Το παράθυρο μεταφύτευσης ανοίγει',
    'campaign_apr_body': 'Σκληραγωγήστε τα φυτά και προετοιμάστε το χώμα — η μεταφύτευση ξεκινά τώρα.',
    'campaign_jul_title': '🥕 Ώρα συγκομιδής!',
    'campaign_jul_body': 'Καταγράψτε την πρώτη σας συγκομιδή και δείτε πόσο αξίζει ο κήπος σας.',
    'campaign_sep_title': '🌷 Φυτέψτε ανοιξιάτικους βολβούς',
    'campaign_sep_body': 'Τουλίπες, νάρκισσοι και κρόκοι φυτεύονται τώρα για μια ανθισμένη άνοιξη.',
    'campaign_nov_title': '📓 Σκεφτείτε την καλλιέργεια της χρονιάς',
    'campaign_nov_body': 'Τι πήγε καλά; Σημειώστε το — η μνήμη ξεθωριάζει μέχρι την άνοιξη.',
  },
};

/// Locale-aware lookup for [NotificationService] strings.
///
/// Why this exists: NotificationService runs without a BuildContext (it
/// schedules from background callbacks and from main.dart wiring), so it
/// can't reach AppLocalizations the usual way. We hold a locale code
/// here and look up translations from the inline [notificationStrings]
/// map. Swedish is the source-of-truth fallback for missing keys and
/// missing locales — better a Swedish reminder than no reminder.
class NotificationStrings {
  String _localeCode = 'sv';

  void setLocale(String localeCode) {
    final lang = localeCode.split(RegExp(r'[-_]')).first.toLowerCase();
    if (notificationStrings.containsKey(lang)) {
      _localeCode = lang;
    } else if (notificationStrings.containsKey('en')) {
      _localeCode = 'en';
    } else {
      _localeCode = 'sv';
    }
  }

  String get localeCode => _localeCode;

  String _get(String key) {
    return notificationStrings[_localeCode]?[key] ??
        notificationStrings['sv']?[key] ??
        key;
  }

  String _format(String key, Map<String, String> args) {
    var text = _get(key);
    args.forEach((k, v) {
      text = text.replaceAll('{$k}', v);
    });
    return text;
  }

  String bodyNow(String action) => _format('body_now', {'action': action});
  String bodyPre(String action) => _format('body_pre', {'action': action});

  String actionForsa() => _get('action_forsa');
  String actionDirekt() => _get('action_direkt');
  String actionUtplant() => _get('action_utplant');
  String actionSkord() => _get('action_skord');

  String labelForsa() => _get('label_forsa');
  String labelDirekt() => _get('label_direkt');
  String labelUtplant() => _get('label_utplant');
  String labelSkord() => _get('label_skord');
  String labelHarden() => _get('label_harden');

  String wishlistBody(String action) =>
      _format('wishlist_body', {'action': action});
  String wishlistPre(String action) =>
      _format('wishlist_pre', {'action': action});

  String hardenBody() => _get('harden_body');

  String careBody(String title, String description) =>
      _format('care_body', {'title': title, 'description': description});
  String carePre(String title) => _format('care_pre', {'title': title});

  String digestTitle() => _get('digest_title');
  String digestBodyOne(String month, String line) =>
      _format('digest_body_one', {'month': month, 'line': line});
  String digestBodyMany(String month, String lines, {required bool hasMore}) =>
      _format('digest_body_many', {
        'month': month,
        'lines': lines,
        'more': hasMore ? _get('digest_more') : _get('digest_end_dot'),
      });

  String monthName(int month) => _get('month_$month');

  String frostTitle() => _get('frost_title');
  String frostBodyOne(String temp, String name) =>
      _format('frost_body_one', {'temp': temp, 'name': name});
  String frostBodyMany(String temp, String names, {required bool hasMore}) =>
      _format('frost_body_many', {
        'temp': temp,
        'names': names,
        'more': hasMore ? _get('digest_more') : '',
      });

  String heatwaveTitle() => _get('heatwave_title');
  String heatwaveBody() => _get('heatwave_body');

  String dryTitle() => _get('dry_title');
  String dryBodyHistorical(String mm) =>
      _format('dry_body_historical', {'mm': mm});
  String dryBodyForecast() => _get('dry_body_forecast');

  String campaignTitle(int month) =>
      _get('campaign_${_monthSlug(month)}_title');
  String campaignBody(int month) =>
      _get('campaign_${_monthSlug(month)}_body');

  String _monthSlug(int month) => switch (month) {
        2 => 'feb',
        3 => 'mar',
        4 => 'apr',
        7 => 'jul',
        9 => 'sep',
        11 => 'nov',
        _ => 'feb',
      };
}
